version: '3.8'
services:
  php-apache:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"
    networks:
      - web-network
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - web-network
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  web-network:
    driver: bridge

volumes:
  db_data:
